GET http://localhost:8080/people

###
GET http://localhost:8080/condition

###
POST http://localhost:8080/people
Content-Type: application/json

{
    "name": "Kirill",
    "age": 21
}

###
GET http://localhost:8080/