version: '3'
services:
  go-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    
    
  redis:
    image: "redis"
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - $HOME/redis:/redis


      
